name: Build Playground

on: [pull_request]

jobs:
  build-playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Playground
        run: npm run play:build
      - name: Run Playground
        run: npm run play:start
        env:
          LD_SDK_KEY: ${{secrets.LD_SDK_KEY}}
          USER_KEY: ${{secrets.USER_KEY}}
          EMAIL: ${{secrets.EMAIL}}
          FLAG_KEY: ${{secrets.FLAG_KEY}}
