name: Tests

on: [pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Cypress install
        uses: cypress-io/github-action@v3
        with:
          runTests: false
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          install: false
          working-directory: ./playground
          build: npm run play:build
          start: npm run play:start
          wait-on: http://localhost:3000
        env:
          LD_SDK_KEY: ${{secrets.LD_SDK_KEY}}
          USER_KEY: ${{secrets.USER_KEY}}
          EMAIL: ${{secrets.EMAIL}}
          FLAG_KEY: ${{secrets.FLAG_KEY}}
